version: '3.8'

services:
  server:
    container_name: backend
    restart: always
    build: ./server
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    container_name: "database"
    restart: always
    build: ./database
    ports:
      - "5432:5432"